config/routes.rb
CloudComputing::Application.routes.draw do
  resources :topics, only: [:show, :index]

  resources :blocks, only: [:show, :index]

  resources :posts

  resources :messages

  mount Ckeditor::Engine => '/ckeditor'
  
  get "carousel/index"

  get "category/index"
  get "articles/index"
  
  namespace :attachment do
    get '', :action => :index
    post '', :action => :upload
  end
  
  namespace :login do
    get '', :action => :index
    post '', :action => :index
  end

  resources :personal
  resources :visitor_index, only: [:index, :show]
  resources :category
  resources :articles do
    get "tag", :action => :tag
    member do
      get 'raw'
    end
  end
  resources :comments, :only => [:create]
  resources :admin, :only => [:index]

  namespace :admin do
    get '', :action => :index
    resources :lesson_table, only: [:edit, :destroy, :index, :update] do
      member do
        get '', :action => :index
        get 'new_lesson'
      end
    end
    get 'login'
    post 'login', :action => :auth
    resources :category, only: [:edit, :destroy, :index, :update] do
      member do
        get '', :action => :index
        get 'new_sub'
        get 'upward'
        get 'downward'
        get 'switch_show'
      end
    end
    resources :article, only: [:edit, :destroy, :index, :update] do
      member do
        get '', :action => :index
        get 'add'
      end
    end
    resources :user, only: [:index, :edit, :update, :show] do
      member do
        get 'switch/:priviledge', :action => :switch
      end
    end
    resources :priviledge, only: [:show, :index] do
      member do
      end
    end
    resources :carousel
    match 'plugins/carousel' => 'carousel#index'
    match 'carousel/add' => 'carousel#add'
    resources :plugins, only: [:index, :edit] do
      member do
        get '', :action => :index
        post 'enable', :action => :toggle_enable
      end
    end

    resources :topics, only: [:index, :show, :edit, :destroy, :update] do
      member do
        get 'new_sub'
        get 'upward'
        get 'downward'
      end
    end
  end

  root :to => "visitor_index#show"

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :tags
  has_many :comments
  attr_accessible :author, :title, :category, :content

  def update_tags(all_tags)
    self.tags = all_tags
  end
end

app/controllers/admin/article_controller.rb
class Admin::ArticleController < AdminController
  def index
    @articles = Article.all
  end
  
  def update
    @article = Article.find params[:id]
    all_tags = Tag.sanitize(params[:article][:tags])
    #params[:article][:tags] = all_tags
    @article.update_tags(all_tags)
    @article.save!
    params[:article].delete(:tags)
    @article.update_attributes!(params[:article])
    flash[:notice] = "#{@article.title} was successfully updated."
    redirect_to edit_admin_article_path(@article)
  end
  
  def edit
    @article = Article.find params[:id]
    @all_tag_string = String.new
    if @article.tags
      @article.tags.each do |tag|
        @all_tag_string += (tag.name + ", ")
      end
    end
  end
  
  def destroy
    article = Article.find params[:id]
    article.destroy
    flash[:notice] = "Article '#{article.title}' deleted."
    redirect_to admin_article_path()
  end
  
  def add
    article = Article.create(:category => (Article.find params[:id]).category)
    redirect_to edit_admin_article_path(article)
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
 
  def create
    @article = Article.create!(params[:article])
    redirect_to articles_path
  end
  
  def new
  end

  def edit
  end

  def show
    id = params[:id]
    id ||= 0
    @article = Article.find(id)
    
    @comments = @article.comments
    @tags = @article.tags
    @category = @article.category
    @categories = Category.find_top_categories
    
    @trace_category = []
    @trace_category.unshift(@i = @category)
    while @i.parent != 0
      @i = Category.find(@i.parent)
      @trace_category.unshift @i
    end
  end
  
  def raw
    id = params[:id]
    id ||= 0
    @article = Article.find(id)
    render :layout => false
  end

  def tag
    tag_name = params[:tag_name]
    @tag = Tag.find_by_name(tag_name)
    @articles = Tag.get_all_articles(tag_name)
  end

  def update
    print("WTF!!")
  end

  def destroy
  end
end

app/views/articles/_comment.html.haml
%h1
  This is a test

app/views/articles/_new_comment.html.haml
= form_tag({:controller => "comments", :action => "create"}, :method => 'post') do
  = label_tag(:content, "My comment")
  = text_field_tag :content
  = submit_tag "Submit", :class => "btn btn-default"

app/views/articles/edit.html.haml
%h1 XueTang Project
= form_tag article_path(@article), :method => :put do
  = label :article, :title, 'Title'
  = text_field :article, :title

  = label :article, :author, 'Author'
  = text_field :article, :author

  = label :article, :content, 'Text'
  = text_area :article, :content
  %br
  = submit_tag 'Save Changes'

app/views/articles/index.html.haml
%h1 XueTang Project
%table#Articles
  %thead
    %tr
      %th Title
      %th Author
    %tbody
      - @articles.each do |article|
        %tr
          %td= article.title
          %td= article.author
%button= link_to "new", new_article_path

app/views/articles/new.html.haml
%h1 XueTang Project
= form_tag articles_path, :method => :post do
  = label :article, :title, 'Title'
  = text_field :article, :title

  = label :article, :author, 'Author'
  = text_field :article, :author

  = label :article, :content, 'Text'
  = text_area :article, :content
  %br
  = submit_tag 'submit'

/%h1 XueTang Project
/%form{:id => 'Information', :method => 'post', :link_to => article_path}
/  %label= 'title'
/  %input#Title
/  %label= 'text'
/  %textarea#Text
/  %button{:type => 'reset'}= 'reset'
/  %button{:type => 'submit'}= 'submit'

app/views/articles/raw.html.haml
= raw(@article.content)

app/views/articles/show.html.haml
%div#br
  %ul.nav.nav-tabs
    - @categories.each do |category|
      %li{ :class => (params[:id] == category.id.to_s)?'active':nil }
        =link_to "#{category.name}", category_path(category)
    %li{:style => "float: right"}= link_to "Home", visitor_index_path()
  %ol.breadcrumb
    - @trace_category.each do |category|
      %li
        = link_to "#{category.name}", category_path(category)
    %li.active #{@article.title}
  %div#article_table
    %div.row
      %div#firstline.col-md-12.text-center
        %h3
          = @article.title
    %div.row
      %div.col-md-2.text-left
        = "author: #{@article.author}"
      %div.col-md-8.text-center
        = "create date: #{@article.created_at}"
      %div.col-md-2.text-right
        = "category: #{@article.category.name}"
    %ul.pager
      - @tags.each do |tag|
        %li
          = link_to tag.name, article_tag_path(@article.id, :tag_name => tag.name)
    %div.row.hero-unit#content
      %div.col-md-10.text-left{:style => "padding-left:0px;padding-right:0px;"}
        %iframe{:src => raw_article_path(@article), :scrolling => "no", :width => "100%", :onload => "javascript: this.style.height = this.contentWindow.document.body.scrollHeight + 'px'; this.style.border = 0;"}
    %table.table
      - @comments.each do |comment|
        = render "comment"
    %div
      = render "new_comment"
  %div#back.btn.btn-link= link_to "back", category_path(@article.category)

app/views/articles/tag.html.haml
%h1
  = @tag.name
- if @articles
  %table.table.table-bordered
    %tbody
      %tr#firstline
        %td Title
        %td Author
        %td id
      - @articles.each do |article|
        %tr.articles
          %td= link_to "#{article.title}", article_path(article)
          %td= article.author
          %td= article.id