config/routes.rb
CloudComputing::Application.routes.draw do
  resources :topics, only: [:show, :index]

  resources :blocks, only: [:show, :index]

  resources :posts

  resources :messages

  mount Ckeditor::Engine => '/ckeditor'
  
  get "carousel/index"

  get "category/index"
  get "articles/index"
  
  namespace :attachment do
    get '', :action => :index
    post '', :action => :upload
  end
  
  namespace :login do
    get '', :action => :index
    post '', :action => :index
  end

  resources :personal
  resources :visitor_index, only: [:index, :show]
  resources :category
  resources :articles do
    get "tag", :action => :tag
    member do
      get 'raw'
    end
  end
  resources :comments, :only => [:create]
  resources :admin, :only => [:index]

  namespace :admin do
    get '', :action => :index
    resources :lesson_table, only: [:edit, :destroy, :index, :update] do
      member do
        get '', :action => :index
        get 'new_lesson'
      end
    end
    get 'login'
    post 'login', :action => :auth
    resources :category, only: [:edit, :destroy, :index, :update] do
      member do
        get '', :action => :index
        get 'new_sub'
        get 'upward'
        get 'downward'
        get 'switch_show'
      end
    end
    resources :article, only: [:edit, :destroy, :index, :update] do
      member do
        get '', :action => :index
        get 'add'
      end
    end
    resources :user, only: [:index, :edit, :update, :show] do
      member do
        get 'switch/:priviledge', :action => :switch
      end
    end
    resources :priviledge, only: [:show, :index] do
      member do
      end
    end
    resources :carousel
    match 'plugins/carousel' => 'carousel#index'
    match 'carousel/add' => 'carousel#add'
    resources :plugins, only: [:index, :edit] do
      member do
        get '', :action => :index
        post 'enable', :action => :toggle_enable
      end
    end

    resources :topics, only: [:index, :show, :edit, :destroy, :update] do
      member do
        get 'new_sub'
        get 'upward'
        get 'downward'
      end
    end
  end

  root :to => "visitor_index#show"

end

app/controllers/visitor_index_controller.rb
class VisitorIndexController < ApplicationController
  def index
    redirect_to visitor_index_path(0), params
  end
 
  def create
  end
  
  def new
  end

  def edit
  end

  def show
    @temporary_user = get_temporary_user
    
    @articles = Article.all
    @top_categories = Category.find_top_categories
    @top_categories_to_show = Category.find_top_categories_to_show
    @subcategories = {}
    @top_categories_to_show.each do |category|
      @subcategories[category] = Category.find_sub_categories(category)
    end

    @classrooms = Lesson.get_all_classrooms
    @departments = Lesson.get_all_departments
    if params.has_key?(:classroom)
      lessons = Lesson.find_all_by_classroom(params[:classroom])
    elsif params.has_key?(:department)
      lessons = Lesson.find_all_by_department(params[:department])
    else
      lessons = Lesson.all
    end
    @table = Hash.new
    
    lessons.each do |lesson|
      if @table.has_key?(lesson.row)
        rank = @table[lesson.row]
      else
        rank = Hash.new
      end
      if rank.has_key?(lesson.column)
        rank[lesson.column] << lesson
      else
        rank[lesson.column] = [lesson]
      end
      @table[lesson.row] = rank
    end
  end

  def update
  end

  def destroy
  end
end

app/helpers/visitor_index_helper.rb
module VisitorIndexHelper
  def generate_lesson_table(row, col, table_data)
    str = Array.new
    if table_data.has_key?(row)
      row_data = table_data[row]
      if row_data.has_key?(col)
        row_data[col].each do |lesson|
          str << ["#{lesson.name}", "At #{lesson.classroom}"]
        end
      end
    end
    return str
  end
end

app/views/visitor_index/show.html.haml
%div#br.row
  %ul#navigator.nav.nav-tabs
    - @top_categories.each do |category|
      %li
        =link_to "#{category.name}", category_path(category)
    %li{:style => "float: right"}
      - if @temporary_user
        =link_to "Personal page", personal_path(@temporary_user.id)
%div.row
  %div.col-md-5
    =render "carousel" if Plugins.find_by_name "carousel"
-@top_categories_to_show.each do |category|
  %div.col-md-6
    %div.panel.panel-default
      %div.panel-heading
        =category.name
      %ul.list-group.nav
        -@subcategories[category].each do |subcategory|
          %li.list-group-item.sub-category
            = link_to "#{subcategory.name}", category_path(subcategory)
      %div.panel-body{:style=>'padding:0px;'}
      %table.table.table-condensed.table-bordered.table-hover{:id=>category.name}
        -category.articles.each do |article|
          %tr
            %td= link_to "#{article.title}", article_path(article)
            -if article.created_at.to_a[3] == Time.now.to_a[3] && article.created_at.to_a[4] == Time.now.to_a[4] && article.created_at.to_a[5] == Time.now.to_a[5]
              %td= article.created_at.to_s.scan(/([^ ]+)/).flatten[1]
            -else
              %td= article.created_at.to_s.scan(/([^ ]+)/).flatten[0]
            %td= article.author

%div.row
  %div.col-md-10.col-md-offset-1
    %div.panel.panel-default
      %div.panel-heading.panel-title{:style => 'text-align:center;'} 课程表
      %div.panel-body{:style=>'padding:5px;'}
        %div.btn-group
          %button.btn.btn-default.dropdown-toggle{:type=>'button','data-toggle'=>'dropdown'}
            教室
            %span.caret
          %ul.dropdown-menu{:role=>'menu'}
            -@classrooms.each do |classroom|
              %li= link_to classroom,visitor_index_path(:id=>1,:classroom=>classroom)
            %li= link_to '全部', visitor_index_path(:id=>1)
        %div.btn-group
          %button.btn.btn-default.dropdown-toggle{:type=>'button','data-toggle'=>'dropdown'}
            系别
            %span.caret
          %ul.dropdown-menu{:role=>'menu'}
            -@departments.each do |dep|
              %li= link_to dep,visitor_index_path(:id=>1,:department=>dep)
            %li= link_to '全部', visitor_index_path(:id=>1)
      %table.table.table-bordered.table-hover
        %tr
          %th Mon.
          %th Tue.
          %th Wed.
          %th Thu.
          %th Fri.
          %th Sat.
          %th Sun.
        - (1..6).each do |row|
          %tr
            - (1..7).each do |col|
              %td
                -generate_lesson_table(row, col, @table).each do |le|
                  %div.label.label-primary
                    -le.each do |line|
                      =line
                      %br
                  %br