config/routes.rb
CloudComputing::Application.routes.draw do
  resources :topics, only: [:show, :index]

  resources :blocks, only: [:show, :index]

  resources :posts

  resources :messages

  mount Ckeditor::Engine => '/ckeditor'
  
  get "carousel/index"

  get "category/index"
  get "articles/index"
  
  namespace :attachment do
    get '', :action => :index
    post '', :action => :upload
  end
  
  namespace :login do
    get '', :action => :index
    post '', :action => :index
  end

  resources :personal
  resources :visitor_index, only: [:index, :show]
  resources :category
  resources :articles do
    get "tag", :action => :tag
    member do
      get 'raw'
    end
  end
  resources :comments, :only => [:create]
  resources :admin, :only => [:index]

  namespace :admin do
    get '', :action => :index
    resources :lesson_table, only: [:edit, :destroy, :index, :update] do
      member do
        get '', :action => :index
        get 'new_lesson'
      end
    end
    get 'login'
    post 'login', :action => :auth
    resources :category, only: [:edit, :destroy, :index, :update] do
      member do
        get '', :action => :index
        get 'new_sub'
        get 'upward'
        get 'downward'
        get 'switch_show'
      end
    end
    resources :article, only: [:edit, :destroy, :index, :update] do
      member do
        get '', :action => :index
        get 'add'
      end
    end
    resources :user, only: [:index, :edit, :update, :show] do
      member do
        get 'switch/:priviledge', :action => :switch
      end
    end
    resources :priviledge, only: [:show, :index] do
      member do
      end
    end
    resources :carousel
    match 'plugins/carousel' => 'carousel#index'
    match 'carousel/add' => 'carousel#add'
    resources :plugins, only: [:index, :edit] do
      member do
        get '', :action => :index
        post 'enable', :action => :toggle_enable
      end
    end

    resources :topics, only: [:index, :show, :edit, :destroy, :update] do
      member do
        get 'new_sub'
        get 'upward'
        get 'downward'
      end
    end
  end

  root :to => "visitor_index#show"

end

app/controllers/admin/lesson_table_controller.rb
class Admin::LessonTableController < AdminController
  before_filter :validate, :except => [:index]

  def index
    @lessons = Hash.new

    if params[:sort] == "classroom"
      @table_head = Lesson.get_all_classrooms
      @table_head.each do |classroom|
        @lessons[classroom.to_sym] = Lesson.find_all_by_classroom(classroom)
      end
    elsif params[:sort] == "department"
      @table_head = Lesson.get_all_departments
      @table_head.each do |department|
        @lessons[department.to_sym] = Lesson.find_all_by_department(department)
      end
    else
      @table_head = ["All Lessons"]
      @lessons["All Lessons"] = Lesson.all
    end
  end

  def edit
    @lesson = Lesson.find params[:id]
  end

  def update
    @lesson = Lesson.find params[:id]
    @lesson.update_attributes!(params[:lesson])
    flash[:notice] = "#{@lesson.name} was successfully updated!"
    redirect_to admin_lesson_table_path
  end

  def new_lesson
    new_les = {:name => "Unknown", :row => 0, :column => 0, :classroom => "Unknown", :department => "Unknown"}
    Lesson.create!(new_les)
    redirect_to admin_lesson_table_path()
  end

  def destroy
    lesson = Lesson.find(params[:id])
    lesson.destroy
    flash[:notice] = "Lesson '#{lesson.name}' deleted."
    redirect_to admin_lesson_table_path()
  end

private
  def validate
    tem_user = get_temporary_user
    priv = Priviledge.find_by_name("user_management")
    if !tem_user.has_priviledge?(priv)
      flash[:notice] = "You are not authorized to do so!"
      redirect_to admin_index_path and return
    end
  end
end

app/helpers/admin/lesson_table_helper.rb
module Admin::LessonTableHelper
end

app/views/admin/lesson_table/edit.html.haml
%h1 Edit Lesson
%div.row-fluid
  %div.col-md-2
    = render "nav"
  %div.col-md-5
    = form_tag admin_lesson_table_path(@lesson), :method => :put do
      %div.form-group
        = label :lesson, :name, "Name"
        = text_field :lesson, 'name', :value => @lesson.name, :placeholder => "Name", :class => "form-control"
      %div.form-group
        = label :lesson, :column, "Week"
        = text_field :lesson, 'column', :value => @lesson.column, :placeholder => "Column", :class => "form-control"
      %div.form-group
        = label :lesson, :row, "Period"
        = text_field :lesson, 'row', :value => @lesson.row, :placeholder => "Row", :class => "form-control"
      %div.form-group
        = label :lesson, :classroom, "Classroom"
        = text_field :lesson, 'classroom', :value => @lesson.classroom, :placeholder => "Classroom", :class => "form-control"
      %div.form-group
        = label :lesson, :department, "Department"
        = text_field :lesson, 'department', :value => @lesson.department, :placeholder => "Department", :class => "form-control"
      = submit_tag 'Update Lesson Info', :class => "btn btn-default"

app/views/admin/lesson_table/index.html.haml
%h1 Edit Lessons
%div.row-fluid
  %div.col-md-2
    =render "nav"
  %div.col-md-10
    %div.btn-group
      = link_to "Sorted by Classroom", admin_lesson_table_path(:id => 0, :sort => "classroom"), :class => "btn btn-default btn-lg", :role => "button"
      = link_to "Sorted by Department", admin_lesson_table_path(:id => 0, :sort => "department"), :class => "btn btn-default btn-lg", :role => "button"
      = link_to "Unsorted", admin_lesson_table_path(:id => 0), :class => "btn btn-default btn-lg", :role => "button"
      = link_to "Add new lesson", "/admin/lesson_table/0/new_lesson", :class => "btn btn-default btn-lg", :role => "button"
    - @lessons.each do |key, content|
      %table.table.table-bordered.table-hover{:id => key}
        %thead
          %tr{:colspan => "6"}
            %th
              %span{:style => "font-size: 16px"}
                = key
          %tr
            %th Name
            %th Day/Rank
            %th Classroom
            %th Department
            %th Edit
            %th Delete
        %tbody
          - content.each do |lesson|
            %tr
              %td= lesson.name
              %td= "#{lesson.column}/#{lesson.row}"
              %td= lesson.classroom
              %td= lesson.department
              %td= link_to link_to image_tag("edit.jpg", :height => "32", :width => "32"), edit_admin_lesson_table_path(lesson.id), :id => lesson.name+"_edit"
              %td= link_to link_to image_tag("delete.jpg", :height => "32", :width => "32"), admin_lesson_table_path(:id => lesson.id), :method => "delete", :confirm => "Are you sure?", :id => lesson.name+"_delete"

%br