config/routes.rb
CloudComputing::Application.routes.draw do
  resources :topics, only: [:show, :index]

  resources :blocks, only: [:show, :index]

  resources :posts

  resources :messages

  mount Ckeditor::Engine => '/ckeditor'
  
  get "carousel/index"

  get "category/index"
  get "articles/index"
  
  namespace :attachment do
    get '', :action => :index
    post '', :action => :upload
  end
  
  namespace :login do
    get '', :action => :index
    post '', :action => :index
  end

  resources :personal
  resources :visitor_index, only: [:index, :show]
  resources :category
  resources :articles do
    get "tag", :action => :tag
    member do
      get 'raw'
    end
  end
  resources :comments, :only => [:create]
  resources :admin, :only => [:index]

  namespace :admin do
    get '', :action => :index
    resources :lesson_table, only: [:edit, :destroy, :index, :update] do
      member do
        get '', :action => :index
        get 'new_lesson'
      end
    end
    get 'login'
    post 'login', :action => :auth
    resources :category, only: [:edit, :destroy, :index, :update] do
      member do
        get '', :action => :index
        get 'new_sub'
        get 'upward'
        get 'downward'
        get 'switch_show'
      end
    end
    resources :article, only: [:edit, :destroy, :index, :update] do
      member do
        get '', :action => :index
        get 'add'
      end
    end
    resources :user, only: [:index, :edit, :update, :show] do
      member do
        get 'switch/:priviledge', :action => :switch
      end
    end
    resources :priviledge, only: [:show, :index] do
      member do
      end
    end
    resources :carousel
    match 'plugins/carousel' => 'carousel#index'
    match 'carousel/add' => 'carousel#add'
    resources :plugins, only: [:index, :edit] do
      member do
        get '', :action => :index
        post 'enable', :action => :toggle_enable
      end
    end

    resources :topics, only: [:index, :show, :edit, :destroy, :update] do
      member do
        get 'new_sub'
        get 'upward'
        get 'downward'
      end
    end
  end

  root :to => "visitor_index#show"

end

app/models/category.rb
class Category < ActiveRecord::Base

attr_accessible :description, :name, :option, :parent, :order, :show_on_index
  # parent is its parent's id, pointing to a category record. 0(default) for root categories.
  
  has_many :articles
  serialize :option, Hash
  
  after_create :set_order_attribute, :set_show_on_index_attribute

  def tree_plant()
    sub_cat = Category.find_sub_categories(self.id)
    result = Array.new

    if sub_cat
      sub_cat.each do |cat|
        result << cat.tree_plant
      end
      return {self => result}
    else
      return self
    end
  end

  def set_order_attribute
    self.order = id if order.nil?
    self.save
  end
  
  def set_show_on_index_attribute
    if self.parent == 0 && self.show_on_index != 'shown'
      self.show_on_index = 'hidden'
    elsif self.parent != 0
      self.show_on_index = 'unavailable'
    end
    self.save
  end
  
  def switch_show
    if self.show_on_index == 'shown'
      self.show_on_index = 'hidden'
    elsif self.show_on_index == 'hidden'
      self.show_on_index = 'shown'
    end
    self.save
  end
  
  def push_sub_categories(category_list, repeat)
    Category.find_sub_categories(id).each do
      |sub_category|
      category_list << {:prefix => "> " * repeat + "- ", :content => sub_category}
      sub_category.push_sub_categories(category_list, repeat + 1)
    end
  end
  
  def self.find_top_categories
    Category.find_all_by_parent(0, :order => '"order"')
  end
  
  def self.find_top_categories_to_show
    temp = []
    Category.find_all_by_parent(0, :order => '"order"').each do |cat|
      if cat.show_on_index == 'shown'
        temp += [cat]
      end
    end
    return temp
  end

  def self.find_sub_categories(parent)
    Category.find_all_by_parent(parent, :order => '"order"')
  end

  def self.category_tree
    cat_tree = Category.find_top_categories
    result = Array.new
    cat_tree.each do |cat|
      result << cat.tree_plant()
    end
    return result
  end

  def generate_related_priviledges(tem_user)
    privs = [
             {:name => "edit_category_" + self.id.to_s, :description => "Empty"},
             {:name => "delete_category_" + self.id.to_s, :description => "Empty"},
             {:name => "add_articles_under_" + self.id.to_s, :description => "Empty"},
             {:name => "edit_articles_under_" + self.id.to_s, :description => "Empty"},
             {:name => "delete_articles_under_" + self.id.to_s, :description => "Empty"}]
    privs.each do |priv|
      new_priv = Priviledge.create!(priv)
      tem_user.priviledges << new_priv
    end
  end

end

app/controllers/admin/category_controller.rb
class Admin::CategoryController < AdminController
  before_filter :validate_edit, :only => [:new_sub, :edit, :upward, :downward, :switch_show, :update]
  before_filter :validate_delete, :only => :destroy
  def index
    @categories = []
    Category.find_top_categories.each do
      |t|
      @categories << {:prefix => "- ", :content => t}
      t.push_sub_categories(@categories, 1)
    end
  end
  
  def new_sub
    new_cat = Category.create!(:name => "(new category)", :parent => params[:id])
    tem_user = get_temporary_user
    new_cat.generate_related_priviledges(tem_user)
    redirect_to admin_category_path()
  end
  
  def upward
    @last = nil
    Category.find_sub_categories(Category.find(params[:id]).parent).each do
      |t|
      if (t.id.to_s == params[:id] and @last != nil)
        @torder = t.order
        t.order = @last.order
        t.save
        @last.order = @torder
        @last.save
      end
      @last = t
    end
    redirect_to admin_category_path()
  end
  
  def downward
    @last = nil
    Category.find_sub_categories(Category.find(params[:id]).parent).each do
      |t|
      if (@last != nil and @last.id.to_s == params[:id])
        @torder = t.order
        t.order = @last.order
        t.save
        @last.order = @torder
        @last.save
      end
      @last = t
    end
    redirect_to admin_category_path()
  end

  def edit
    @category = Category.find params[:id]
  end

  #def show
  #  redirect_to admin_category_path()
  #end

  def update
    @category = Category.find params[:id]
    @category.update_attributes!(params[:category])
    flash[:notice] = "#{@category.name} was successfully updated."
    redirect_to admin_category_path()
  end

  def destroy # database leak(remaining )...
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category '#{@category.name}' deleted."
    redirect_to admin_category_path()
  end
  
  def switch_show
    @category = Category.find params[:id]
    @category.switch_show
    flash[:notice] = "Category #{@category.name}'s visibility on index has been switched."
    redirect_to admin_category_path()
  end

#  private
  def validate_edit
    if params[:id] == "0"
      validate_topcategory_edit
    else
      validate_subcategory_edit
    end
  end

  def validate_topcategory_edit
    tem_user = get_temporary_user
    priv = Priviledge.find_by_name("edit_top_category")
    if !tem_user.has_priviledge?(priv)
      flash[:notice] = "You are not authorized to do so!"
      redirect_to admin_index_path and return
    end
  end
  
  def validate_subcategory_edit
    cat = Category.find(params[:id])
    tem_user = get_temporary_user
    priv = Priviledge.find_by_name("edit_category_" + cat.id.to_s)
    if !tem_user.has_priviledge?(priv)
      flash[:notice] = "You are not authorized to do so!"
      redirect_to admin_index_path and return
    end
  end

  def validate_delete
    tem_user = get_temporary_user
    cat = Category.find(params[:id])
    priv = Priviledge.find_by_name("delete_category_" + cat.id.to_s)
    if !tem_user.has_priviledge?(priv)
      flash[:notice] = "You are not authorized to do so!"
      redirect_to admin_index_path and return
    end
  end

  def generate_related_priviledges(new_cat)
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    all_category = Category.all
    @categories = Array.new
    all_category.each do |cat|
      if cat.parent == 0
        @categories << cat
      end
    end
  end
 
  def create
  end
  
  def new
  end

  def edit
  end

  def show
    @temporary_user = get_temporary_user
    id = params[:id]
    id ||= 0
    @current_category = Category.find(id)
    @articles = @current_category.articles
    @top_category = Category.find_top_categories
    @sub_category = Category.find_sub_categories(@current_category.id)
    
    @trace_category = []
    @i = @current_category
    while @i.parent != 0
      @i = Category.find(@i.parent)
      @trace_category.unshift @i
    end
  end

  def update
  end

  def destroy
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/admin/category/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Category
%div.row-fluid
  %div.col-md-2
    =render "nav"
  %div.col-md-10
    = form_tag admin_category_path(@category), :method => :put do
      = label :category, :name, 'Name'
      = text_field :category, 'name', :value => @category.name, :placeholder => "Name"
      %br
      = submit_tag 'Update Category Info', :class => "btn"

app/views/admin/category/index.html.haml
%h1 Category edit list
%div.row-fluid
  %div.col-md-2
    = render "nav"
  %div.col-md-10
    %table.table.table-bordered.table-hover
      %thead
        %tr
          %th Categories
          %th order
          %th id
          %th parent
          %th edit link
          %th delete link
          %th insert link
          %th upward
          %th downward
          %th shown on index
      %tbody
        - @categories.each do |category|
          %tr
            %td= link_to "#{category[:prefix] + category[:content].name}", category_path(category[:content].id)
            %td= category[:content].order
            %td= category[:content].id
            %td= category[:content].parent
            %td= link_to image_tag("edit.jpg", :height => "32", :width => "32"), edit_admin_category_path(category[:content]), :id => category[:content].name+"_edit"
            %td= link_to image_tag("delete.jpg", :height => "32", :width => "32"), admin_category_path(category[:content]), :method => :delete, :confirm => 'Are you sure?', :id => category[:content].name+"_-"
            %td= link_to image_tag("add.jpg", :height => "32", :width => "32"), new_sub_admin_category_path(category[:content]),:id=>category[:content].name+"_+"
            %td= link_to image_tag("up.jpg", :height => "32", :width => "32"), upward_admin_category_path(category[:content]),:id=>category[:content].name+"_up"
            %td= link_to image_tag("down.jpg", :height => "32", :width => "32"), downward_admin_category_path(category[:content]),:id=>category[:content].name+"_down"
            %td
              -if category[:content].show_on_index == "unavailable"
                =link_to "unavailable", "#",{:class => "btn btn-default btn-block"}
              -elsif category[:content].show_on_index == "shown"
                =link_to "shown", switch_show_admin_category_path(category[:content]), {:class => "btn btn-primary btn-block"}
              -else
                =link_to "hidden", switch_show_admin_category_path(category[:content]), {:class => "btn btn-danger btn-block"}
    %br
    = link_to "Insert Top Category", new_sub_admin_category_path(0), {:class => "btn btn-link"}